// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: testdata/testdata.proto

package testdata

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTestDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTestDataRequest) Reset() {
	*x = GetTestDataRequest{}
	mi := &file_testdata_testdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTestDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestDataRequest) ProtoMessage() {}

func (x *GetTestDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_testdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestDataRequest.ProtoReflect.Descriptor instead.
func (*GetTestDataRequest) Descriptor() ([]byte, []int) {
	return file_testdata_testdata_proto_rawDescGZIP(), []int{0}
}

type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Profession    string                 `protobuf:"bytes,3,opt,name=profession,proto3" json:"profession,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_testdata_testdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_testdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_testdata_testdata_proto_rawDescGZIP(), []int{1}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Person) GetProfession() string {
	if x != nil {
		return x.Profession
	}
	return ""
}

type TestDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Persons       []*Person              `protobuf:"bytes,1,rep,name=persons,proto3" json:"persons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestDataResponse) Reset() {
	*x = TestDataResponse{}
	mi := &file_testdata_testdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestDataResponse) ProtoMessage() {}

func (x *TestDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_testdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestDataResponse.ProtoReflect.Descriptor instead.
func (*TestDataResponse) Descriptor() ([]byte, []int) {
	return file_testdata_testdata_proto_rawDescGZIP(), []int{2}
}

func (x *TestDataResponse) GetPersons() []*Person {
	if x != nil {
		return x.Persons
	}
	return nil
}

var File_testdata_testdata_proto protoreflect.FileDescriptor

const file_testdata_testdata_proto_rawDesc = "" +
	"\n" +
	"\x17testdata/testdata.proto\x12\btestdata\x1a\x1cgoogle/api/annotations.proto\"\x14\n" +
	"\x12GetTestDataRequest\"N\n" +
	"\x06Person\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12\x1e\n" +
	"\n" +
	"profession\x18\x03 \x01(\tR\n" +
	"profession\">\n" +
	"\x10TestDataResponse\x12*\n" +
	"\apersons\x18\x01 \x03(\v2\x10.testdata.PersonR\apersons2n\n" +
	"\x0fTestDataService\x12[\n" +
	"\vGetTestData\x12\x1c.testdata.GetTestDataRequest\x1a\x1a.testdata.TestDataResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/test-dataB\x10Z\x0eproto/testdatab\x06proto3"

var (
	file_testdata_testdata_proto_rawDescOnce sync.Once
	file_testdata_testdata_proto_rawDescData []byte
)

func file_testdata_testdata_proto_rawDescGZIP() []byte {
	file_testdata_testdata_proto_rawDescOnce.Do(func() {
		file_testdata_testdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testdata_testdata_proto_rawDesc), len(file_testdata_testdata_proto_rawDesc)))
	})
	return file_testdata_testdata_proto_rawDescData
}

var file_testdata_testdata_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_testdata_testdata_proto_goTypes = []any{
	(*GetTestDataRequest)(nil), // 0: testdata.GetTestDataRequest
	(*Person)(nil),             // 1: testdata.Person
	(*TestDataResponse)(nil),   // 2: testdata.TestDataResponse
}
var file_testdata_testdata_proto_depIdxs = []int32{
	1, // 0: testdata.TestDataResponse.persons:type_name -> testdata.Person
	0, // 1: testdata.TestDataService.GetTestData:input_type -> testdata.GetTestDataRequest
	2, // 2: testdata.TestDataService.GetTestData:output_type -> testdata.TestDataResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_testdata_testdata_proto_init() }
func file_testdata_testdata_proto_init() {
	if File_testdata_testdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testdata_testdata_proto_rawDesc), len(file_testdata_testdata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testdata_testdata_proto_goTypes,
		DependencyIndexes: file_testdata_testdata_proto_depIdxs,
		MessageInfos:      file_testdata_testdata_proto_msgTypes,
	}.Build()
	File_testdata_testdata_proto = out.File
	file_testdata_testdata_proto_goTypes = nil
	file_testdata_testdata_proto_depIdxs = nil
}
