// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: testdata/testdata.proto

package testdata

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TestDataService_GetTestData_FullMethodName = "/testdata.TestDataService/GetTestData"
)

// TestDataServiceClient is the client API for TestDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestDataServiceClient interface {
	GetTestData(ctx context.Context, in *GetTestDataRequest, opts ...grpc.CallOption) (*TestDataResponse, error)
}

type testDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestDataServiceClient(cc grpc.ClientConnInterface) TestDataServiceClient {
	return &testDataServiceClient{cc}
}

func (c *testDataServiceClient) GetTestData(ctx context.Context, in *GetTestDataRequest, opts ...grpc.CallOption) (*TestDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestDataResponse)
	err := c.cc.Invoke(ctx, TestDataService_GetTestData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestDataServiceServer is the server API for TestDataService service.
// All implementations must embed UnimplementedTestDataServiceServer
// for forward compatibility.
type TestDataServiceServer interface {
	GetTestData(context.Context, *GetTestDataRequest) (*TestDataResponse, error)
	mustEmbedUnimplementedTestDataServiceServer()
}

// UnimplementedTestDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTestDataServiceServer struct{}

func (UnimplementedTestDataServiceServer) GetTestData(context.Context, *GetTestDataRequest) (*TestDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTestData not implemented")
}
func (UnimplementedTestDataServiceServer) mustEmbedUnimplementedTestDataServiceServer() {}
func (UnimplementedTestDataServiceServer) testEmbeddedByValue()                         {}

// UnsafeTestDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestDataServiceServer will
// result in compilation errors.
type UnsafeTestDataServiceServer interface {
	mustEmbedUnimplementedTestDataServiceServer()
}

func RegisterTestDataServiceServer(s grpc.ServiceRegistrar, srv TestDataServiceServer) {
	// If the following call pancis, it indicates UnimplementedTestDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TestDataService_ServiceDesc, srv)
}

func _TestDataService_GetTestData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTestDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestDataServiceServer).GetTestData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestDataService_GetTestData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestDataServiceServer).GetTestData(ctx, req.(*GetTestDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TestDataService_ServiceDesc is the grpc.ServiceDesc for TestDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "testdata.TestDataService",
	HandlerType: (*TestDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTestData",
			Handler:    _TestDataService_GetTestData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "testdata/testdata.proto",
}
